version: 2

jobs:
  integrationTests:
    docker:
      - image: web3f/ci-commons:v2.4.4
    steps:
      - checkout
      - setup_remote_docker
      - run:
          description: run integration tests
          command: |
            /scripts/integration-tests.sh

  publishChart:
    docker:
      - image: web3f/ci-commons:v2.4.4
    steps:
      - checkout
      - run:
          command: |
            /scripts/publish-chart.sh


workflows:
  version: 2
  test_and_deploy:
    jobs:
      - integrationTests:
          filters:
            tags:
              only: /.*/

      - publishChart:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
          requires:
            - integrationTests
