environments:
  production:
  ci:

repositories:
- name: jetstack
  url: https://charts.jetstack.io

releases:
- name: cert-manager
  namespace: cert-manager
  chart: jetstack/cert-manager
  version: v0.15.2
