environments:
  production:
  ci:

releases:
- name: prometheus-node-exporter
  chart: https://prometheus-community.github.io/helm-charts
  version: 1.11.1
  values:
  - ./config/prometheus-node-exporter-values.yaml.gotmpl
