environment: ci

origin: base

grafana:
  enabled: true
  password: password
  domain: web3.foundation

cloudflareApiToken: ""

alertRules:
  create: true

issuer:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: devops@web3.foundation

  solvers:
    cloudflare:
      email: cloudflare@web3.foundation    
